// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOAGbfUvKVSsE-uC94nPCKMiW7S83xz3g',
    appId: '1:206563041543:web:fe73e1a3351e170719a5a2',
    messagingSenderId: '206563041543',
    projectId: 'gymfit-917cc',
    authDomain: 'gymfit-917cc.firebaseapp.com',
    storageBucket: 'gymfit-917cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0qvePiMVeLjja1iaN7dZDk7NhQNE2K8Q',
    appId: '1:206563041543:android:ca0330c0407ba6ac19a5a2',
    messagingSenderId: '206563041543',
    projectId: 'gymfit-917cc',
    storageBucket: 'gymfit-917cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADM63JdXSAgGAof6L2oTYLG3xCwJRIQUU',
    appId: '1:206563041543:ios:d43c372b12d9a9b619a5a2',
    messagingSenderId: '206563041543',
    projectId: 'gymfit-917cc',
    storageBucket: 'gymfit-917cc.firebasestorage.app',
    iosBundleId: 'com.example.gymfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADM63JdXSAgGAof6L2oTYLG3xCwJRIQUU',
    appId: '1:206563041543:ios:d43c372b12d9a9b619a5a2',
    messagingSenderId: '206563041543',
    projectId: 'gymfit-917cc',
    storageBucket: 'gymfit-917cc.firebasestorage.app',
    iosBundleId: 'com.example.gymfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOAGbfUvKVSsE-uC94nPCKMiW7S83xz3g',
    appId: '1:206563041543:web:eebdd31324c0c5ec19a5a2',
    messagingSenderId: '206563041543',
    projectId: 'gymfit-917cc',
    authDomain: 'gymfit-917cc.firebaseapp.com',
    storageBucket: 'gymfit-917cc.firebasestorage.app',
  );
}
